//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int groupField;
        
        private int idField;
        
        private string nameField;
        
        private string passwordField;
        
        private string usernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class GroupData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool allow_maintenanceField;
        
        private int idField;
        
        private string nameField;
        
        private bool share_full_desktopField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool allow_maintenance
        {
            get
            {
                return this.allow_maintenanceField;
            }
            set
            {
                this.allow_maintenanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool share_full_desktop
        {
            get
            {
                return this.share_full_desktopField;
            }
            set
            {
                this.share_full_desktopField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class ApplicationData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string applicationPathField;
        
        private string argumentsField;
        
        private int idField;
        
        private string nameField;
        
        private WcfServiceLibrary1.WindowsRect rectField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string applicationPath
        {
            get
            {
                return this.applicationPathField;
            }
            set
            {
                this.applicationPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1.WindowsRect rect
        {
            get
            {
                return this.rectField;
            }
            set
            {
                this.rectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WindowsRect", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class WindowsRect : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BottomField;
        
        private int LeftField;
        
        private int RightField;
        
        private int TopField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bottom
        {
            get
            {
                return this.BottomField;
            }
            set
            {
                this.BottomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Left
        {
            get
            {
                return this.LeftField;
            }
            set
            {
                this.LeftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Right
        {
            get
            {
                return this.RightField;
            }
            set
            {
                this.RightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top
        {
            get
            {
                return this.TopField;
            }
            set
            {
                this.TopField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PresetData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class PresetData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WcfServiceLibrary1.ApplicationData[] AppDataListField;
        
        private int IdField;
        
        private WcfServiceLibrary1.VisionData[] InputDataListField;
        
        private string NameField;
        
        private WcfServiceLibrary1.RemoteVncData[] VncDataListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1.ApplicationData[] AppDataList
        {
            get
            {
                return this.AppDataListField;
            }
            set
            {
                this.AppDataListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1.VisionData[] InputDataList
        {
            get
            {
                return this.InputDataListField;
            }
            set
            {
                this.InputDataListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1.RemoteVncData[] VncDataList
        {
            get
            {
                return this.VncDataListField;
            }
            set
            {
                this.VncDataListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisionData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class VisionData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private string inputStrField;
        
        private string osdStrField;
        
        private WcfServiceLibrary1.WindowsRect rectField;
        
        private string windowStrField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inputStr
        {
            get
            {
                return this.inputStrField;
            }
            set
            {
                this.inputStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string osdStr
        {
            get
            {
                return this.osdStrField;
            }
            set
            {
                this.osdStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1.WindowsRect rect
        {
            get
            {
                return this.rectField;
            }
            set
            {
                this.rectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string windowStr
        {
            get
            {
                return this.windowStrField;
            }
            set
            {
                this.windowStrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteVncData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class RemoteVncData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private string nameField;
        
        private WcfServiceLibrary1.WindowsRect rectField;
        
        private string remoteIpField;
        
        private int remotePortField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1.WindowsRect rect
        {
            get
            {
                return this.rectField;
            }
            set
            {
                this.rectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remoteIp
        {
            get
            {
                return this.remoteIpField;
            }
            set
            {
                this.remoteIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int remotePort
        {
            get
            {
                return this.remotePortField;
            }
            set
            {
                this.remotePortField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SettingData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class SettingData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MatrixColumnField;
        
        private int MatrixRowField;
        
        private int PortEndField;
        
        private int PortStartField;
        
        private string VncPathField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatrixColumn
        {
            get
            {
                return this.MatrixColumnField;
            }
            set
            {
                this.MatrixColumnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatrixRow
        {
            get
            {
                return this.MatrixRowField;
            }
            set
            {
                this.MatrixRowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PortEnd
        {
            get
            {
                return this.PortEndField;
            }
            set
            {
                this.PortEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PortStart
        {
            get
            {
                return this.PortStartField;
            }
            set
            {
                this.PortStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VncPath
        {
            get
            {
                return this.VncPathField;
            }
            set
            {
                this.VncPathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitorData", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public partial class MonitorData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BottomField;
        
        private int LeftField;
        
        private int MonitorIdField;
        
        private string NameField;
        
        private int RightField;
        
        private int TopField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bottom
        {
            get
            {
                return this.BottomField;
            }
            set
            {
                this.BottomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Left
        {
            get
            {
                return this.LeftField;
            }
            set
            {
                this.LeftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonitorId
        {
            get
            {
                return this.MonitorIdField;
            }
            set
            {
                this.MonitorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Right
        {
            get
            {
                return this.RightField;
            }
            set
            {
                this.RightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top
        {
            get
            {
                return this.TopField;
            }
            set
            {
                this.TopField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    public enum DBType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Application = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preset = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisionInput = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteVnc = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monitor = 7,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1", CallbackContract=typeof(IService1Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/RegisterCallback")]
    void RegisterCallback();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
    int AddUser(string name, string userName, string password, int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
    bool EditUser(int userId, string name, string userName, string password, int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveUser", ReplyAction="http://tempuri.org/IService1/RemoveUserResponse")]
    bool RemoveUser(int userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
    WcfServiceLibrary1.UserData[] GetAllUsers();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
    WcfServiceLibrary1.UserData GetUser(int userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGroup", ReplyAction="http://tempuri.org/IService1/AddGroupResponse")]
    int AddGroup(string groupName, bool shareDesktop, bool allowMaintenace, int monitorId, int[] allowApps);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditGroup", ReplyAction="http://tempuri.org/IService1/EditGroupResponse")]
    bool EditGroup(int groupId, string groupName, bool shareDesktop, bool allowMaintenace, int monitorId, int[] appIds);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveGroup", ReplyAction="http://tempuri.org/IService1/RemoveGroupResponse")]
    bool RemoveGroup(int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGroups", ReplyAction="http://tempuri.org/IService1/GetAllGroupsResponse")]
    WcfServiceLibrary1.GroupData[] GetAllGroups();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupByUserId", ReplyAction="http://tempuri.org/IService1/GetGroupByUserIdResponse")]
    WcfServiceLibrary1.GroupData GetGroupByUserId(int userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersInGroup", ReplyAction="http://tempuri.org/IService1/GetUsersInGroupResponse")]
    WcfServiceLibrary1.UserData[] GetUsersInGroup(int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddApplication", ReplyAction="http://tempuri.org/IService1/AddApplicationResponse")]
    int AddApplication(string appName, string extraArguments, string exePath, int left, int top, int right, int bottom);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditApplication", ReplyAction="http://tempuri.org/IService1/EditApplicationResponse")]
    bool EditApplication(int appId, string appName, string exePath, string extraArguments, int left, int top, int right, int bottom);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveApplication", ReplyAction="http://tempuri.org/IService1/RemoveApplicationResponse")]
    bool RemoveApplication(int appId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllApplications", ReplyAction="http://tempuri.org/IService1/GetAllApplicationsResponse")]
    WcfServiceLibrary1.ApplicationData[] GetAllApplications();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAppsWithGroupId", ReplyAction="http://tempuri.org/IService1/GetAppsWithGroupIdResponse")]
    WcfServiceLibrary1.ApplicationData[] GetAppsWithGroupId(int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAppsWithUserId", ReplyAction="http://tempuri.org/IService1/GetAppsWithUserIdResponse")]
    WcfServiceLibrary1.ApplicationData[] GetAppsWithUserId(int userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPreset", ReplyAction="http://tempuri.org/IService1/AddPresetResponse")]
    void AddPreset(string presetName, int userId, System.Collections.Generic.Dictionary<int, WcfServiceLibrary1.WindowsRect> appIds, System.Collections.Generic.Dictionary<int, WcfServiceLibrary1.WindowsRect> vncIds, System.Collections.Generic.Dictionary<int, WcfServiceLibrary1.WindowsRect> inputIds);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/RemovePreset")]
    void RemovePreset(int presetId);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/EditPreset")]
    void EditPreset(int presetId, string presetName, int userId, int[] appIds, int[] vncIds, int[] inputIds);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPresetByUserId", ReplyAction="http://tempuri.org/IService1/GetPresetByUserIdResponse")]
    WcfServiceLibrary1.PresetData[] GetPresetByUserId(int userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPresetIdByPresetNameUserId", ReplyAction="http://tempuri.org/IService1/GetPresetIdByPresetNameUserIdResponse")]
    int GetPresetIdByPresetNameUserId(string presetName, int userId);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/AddOrEditSetting")]
    void AddOrEditSetting(int portStart, int portEnd, int matrixCol, int matrixRow, string vncPath);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/RemoveSetting")]
    void RemoveSetting();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsSettingAdded", ReplyAction="http://tempuri.org/IService1/IsSettingAddedResponse")]
    bool IsSettingAdded();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSetting", ReplyAction="http://tempuri.org/IService1/GetSettingResponse")]
    WcfServiceLibrary1.SettingData GetSetting();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMonitorsList", ReplyAction="http://tempuri.org/IService1/GetMonitorsListResponse")]
    WcfServiceLibrary1.MonitorData[] GetMonitorsList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMonitor", ReplyAction="http://tempuri.org/IService1/AddMonitorResponse")]
    bool AddMonitor(string name, int left, int top, int right, int bottom);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveMonitor", ReplyAction="http://tempuri.org/IService1/RemoveMonitorResponse")]
    bool RemoveMonitor(int monitorId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditMonitor", ReplyAction="http://tempuri.org/IService1/EditMonitorResponse")]
    bool EditMonitor(int monitorId, string name, int left, int top, int right, int bottom);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMonitorByGroupId", ReplyAction="http://tempuri.org/IService1/GetMonitorByGroupIdResponse")]
    WcfServiceLibrary1.MonitorData GetMonitorByGroupId(int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMonitorDataByUserId", ReplyAction="http://tempuri.org/IService1/GetMonitorDataByUserIdResponse")]
    WcfServiceLibrary1.MonitorData GetMonitorDataByUserId(int userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRemoteVncList", ReplyAction="http://tempuri.org/IService1/GetRemoteVncListResponse")]
    WcfServiceLibrary1.RemoteVncData[] GetRemoteVncList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRemoteVnc", ReplyAction="http://tempuri.org/IService1/AddRemoteVncResponse")]
    bool AddRemoteVnc(string name, string ipAdd, int port);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveRemoteVnc", ReplyAction="http://tempuri.org/IService1/RemoveRemoteVncResponse")]
    bool RemoveRemoteVnc(int dataId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditRemoteVnc", ReplyAction="http://tempuri.org/IService1/EditRemoteVncResponse")]
    bool EditRemoteVnc(int dataId, string name, string ipAdd, int port);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllVisionInputs", ReplyAction="http://tempuri.org/IService1/GetAllVisionInputsResponse")]
    WcfServiceLibrary1.VisionData[] GetAllVisionInputs();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddVisionInput", ReplyAction="http://tempuri.org/IService1/AddVisionInputResponse")]
    bool AddVisionInput(string windowObj, string inputObj, string osdObj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveVisionInput", ReplyAction="http://tempuri.org/IService1/RemoveVisionInputResponse")]
    bool RemoveVisionInput(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditVisionData", ReplyAction="http://tempuri.org/IService1/EditVisionDataResponse")]
    bool EditVisionData(int id, string windowObj, string inputObj, string osdObj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSystemSettingsInputCount", ReplyAction="http://tempuri.org/IService1/GetSystemSettingsInputCountResponse")]
    int GetSystemSettingsInputCount();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetSystemSettingsInputCount", ReplyAction="http://tempuri.org/IService1/SetSystemSettingsInputCountResponse")]
    bool SetSystemSettingsInputCount(int count);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Callback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/OnUserDBAdded")]
    void OnUserDBAdded(WcfServiceLibrary1.DBType dbType, int dbIndex);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/OnUserDBEditing")]
    void OnUserDBEditing(WcfServiceLibrary1.DBType dbType, int dbIndex);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/OnUserDBEdited")]
    void OnUserDBEdited(WcfServiceLibrary1.DBType dbType, int dbIndex);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/onUserDBRemoving")]
    void onUserDBRemoving(WcfServiceLibrary1.DBType dbType, int dbIndex);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService1/onUserDBRemoved")]
    void onUserDBRemoved(WcfServiceLibrary1.DBType dbType, int dbIndex);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.DuplexClientBase<IService1>, IService1
{
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void RegisterCallback()
    {
        base.Channel.RegisterCallback();
    }
    
    public int AddUser(string name, string userName, string password, int groupId)
    {
        return base.Channel.AddUser(name, userName, password, groupId);
    }
    
    public bool EditUser(int userId, string name, string userName, string password, int groupId)
    {
        return base.Channel.EditUser(userId, name, userName, password, groupId);
    }
    
    public bool RemoveUser(int userId)
    {
        return base.Channel.RemoveUser(userId);
    }
    
    public WcfServiceLibrary1.UserData[] GetAllUsers()
    {
        return base.Channel.GetAllUsers();
    }
    
    public WcfServiceLibrary1.UserData GetUser(int userId)
    {
        return base.Channel.GetUser(userId);
    }
    
    public int AddGroup(string groupName, bool shareDesktop, bool allowMaintenace, int monitorId, int[] allowApps)
    {
        return base.Channel.AddGroup(groupName, shareDesktop, allowMaintenace, monitorId, allowApps);
    }
    
    public bool EditGroup(int groupId, string groupName, bool shareDesktop, bool allowMaintenace, int monitorId, int[] appIds)
    {
        return base.Channel.EditGroup(groupId, groupName, shareDesktop, allowMaintenace, monitorId, appIds);
    }
    
    public bool RemoveGroup(int groupId)
    {
        return base.Channel.RemoveGroup(groupId);
    }
    
    public WcfServiceLibrary1.GroupData[] GetAllGroups()
    {
        return base.Channel.GetAllGroups();
    }
    
    public WcfServiceLibrary1.GroupData GetGroupByUserId(int userId)
    {
        return base.Channel.GetGroupByUserId(userId);
    }
    
    public WcfServiceLibrary1.UserData[] GetUsersInGroup(int groupId)
    {
        return base.Channel.GetUsersInGroup(groupId);
    }
    
    public int AddApplication(string appName, string extraArguments, string exePath, int left, int top, int right, int bottom)
    {
        return base.Channel.AddApplication(appName, extraArguments, exePath, left, top, right, bottom);
    }
    
    public bool EditApplication(int appId, string appName, string exePath, string extraArguments, int left, int top, int right, int bottom)
    {
        return base.Channel.EditApplication(appId, appName, exePath, extraArguments, left, top, right, bottom);
    }
    
    public bool RemoveApplication(int appId)
    {
        return base.Channel.RemoveApplication(appId);
    }
    
    public WcfServiceLibrary1.ApplicationData[] GetAllApplications()
    {
        return base.Channel.GetAllApplications();
    }
    
    public WcfServiceLibrary1.ApplicationData[] GetAppsWithGroupId(int groupId)
    {
        return base.Channel.GetAppsWithGroupId(groupId);
    }
    
    public WcfServiceLibrary1.ApplicationData[] GetAppsWithUserId(int userId)
    {
        return base.Channel.GetAppsWithUserId(userId);
    }
    
    public void AddPreset(string presetName, int userId, System.Collections.Generic.Dictionary<int, WcfServiceLibrary1.WindowsRect> appIds, System.Collections.Generic.Dictionary<int, WcfServiceLibrary1.WindowsRect> vncIds, System.Collections.Generic.Dictionary<int, WcfServiceLibrary1.WindowsRect> inputIds)
    {
        base.Channel.AddPreset(presetName, userId, appIds, vncIds, inputIds);
    }
    
    public void RemovePreset(int presetId)
    {
        base.Channel.RemovePreset(presetId);
    }
    
    public void EditPreset(int presetId, string presetName, int userId, int[] appIds, int[] vncIds, int[] inputIds)
    {
        base.Channel.EditPreset(presetId, presetName, userId, appIds, vncIds, inputIds);
    }
    
    public WcfServiceLibrary1.PresetData[] GetPresetByUserId(int userId)
    {
        return base.Channel.GetPresetByUserId(userId);
    }
    
    public int GetPresetIdByPresetNameUserId(string presetName, int userId)
    {
        return base.Channel.GetPresetIdByPresetNameUserId(presetName, userId);
    }
    
    public void AddOrEditSetting(int portStart, int portEnd, int matrixCol, int matrixRow, string vncPath)
    {
        base.Channel.AddOrEditSetting(portStart, portEnd, matrixCol, matrixRow, vncPath);
    }
    
    public void RemoveSetting()
    {
        base.Channel.RemoveSetting();
    }
    
    public bool IsSettingAdded()
    {
        return base.Channel.IsSettingAdded();
    }
    
    public WcfServiceLibrary1.SettingData GetSetting()
    {
        return base.Channel.GetSetting();
    }
    
    public WcfServiceLibrary1.MonitorData[] GetMonitorsList()
    {
        return base.Channel.GetMonitorsList();
    }
    
    public bool AddMonitor(string name, int left, int top, int right, int bottom)
    {
        return base.Channel.AddMonitor(name, left, top, right, bottom);
    }
    
    public bool RemoveMonitor(int monitorId)
    {
        return base.Channel.RemoveMonitor(monitorId);
    }
    
    public bool EditMonitor(int monitorId, string name, int left, int top, int right, int bottom)
    {
        return base.Channel.EditMonitor(monitorId, name, left, top, right, bottom);
    }
    
    public WcfServiceLibrary1.MonitorData GetMonitorByGroupId(int groupId)
    {
        return base.Channel.GetMonitorByGroupId(groupId);
    }
    
    public WcfServiceLibrary1.MonitorData GetMonitorDataByUserId(int userId)
    {
        return base.Channel.GetMonitorDataByUserId(userId);
    }
    
    public WcfServiceLibrary1.RemoteVncData[] GetRemoteVncList()
    {
        return base.Channel.GetRemoteVncList();
    }
    
    public bool AddRemoteVnc(string name, string ipAdd, int port)
    {
        return base.Channel.AddRemoteVnc(name, ipAdd, port);
    }
    
    public bool RemoveRemoteVnc(int dataId)
    {
        return base.Channel.RemoveRemoteVnc(dataId);
    }
    
    public bool EditRemoteVnc(int dataId, string name, string ipAdd, int port)
    {
        return base.Channel.EditRemoteVnc(dataId, name, ipAdd, port);
    }
    
    public WcfServiceLibrary1.VisionData[] GetAllVisionInputs()
    {
        return base.Channel.GetAllVisionInputs();
    }
    
    public bool AddVisionInput(string windowObj, string inputObj, string osdObj)
    {
        return base.Channel.AddVisionInput(windowObj, inputObj, osdObj);
    }
    
    public bool RemoveVisionInput(int id)
    {
        return base.Channel.RemoveVisionInput(id);
    }
    
    public bool EditVisionData(int id, string windowObj, string inputObj, string osdObj)
    {
        return base.Channel.EditVisionData(id, windowObj, inputObj, osdObj);
    }
    
    public int GetSystemSettingsInputCount()
    {
        return base.Channel.GetSystemSettingsInputCount();
    }
    
    public bool SetSystemSettingsInputCount(int count)
    {
        return base.Channel.SetSystemSettingsInputCount(count);
    }
}
